version: '2.4'

services:

  gateway:
    container_name: gateway
    build:
      context: services/gateway
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - backend
    ports:
      - 8080
    restart: always

networks:
  backend:

